# Generated by Django 5.1.1 on 2025-02-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_image',
        ),
    ]
